name = "leave-management-app"
main = "src/worker.js"
compatibility_date = "2026-07-13"

[[d1_databases]]
binding = "DB"
database_name = "leavedesk-db"
database_id = 6739e135-aa91-4f2f-8e0a-37159e4474df
migrations_dir = "migrations"

[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "leave-management-attachments"

[vars]
APP_NAME = "LeaveDesk"
